# Generated by Django 5.1.6 on 2025-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Please follow proper naming conventions (e.g., CTC313, etc.) for the delivery address.', max_length=255, null=True),
        ),
    ]
