# Generated by Django 5.1.6 on 2025-03-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_delivery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Order Cancelled', 'Order Cancelled'), ('Preparing Order', 'Preparing Order'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Order Placed', max_length=20),
        ),
    ]
