# Generated by Django 5.1.6 on 2025-03-16 14:48

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.IntegerField(error_messages={'unique': 'This Ateneo Student ID has already been registered.'}, primary_key=True, serialize=False, unique=True, validators=[users.models.user_id_validate])),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(error_messages={'unique': 'This phone number has already been registered.'}, max_length=11, unique=True, validators=[users.models.phone_validate])),
                ('email_address', models.EmailField(error_messages={'invalid': 'Enter a valid Ateneo email.', 'unique': 'This Ateneo Student email has already been registered.'}, max_length=254, unique=True, validators=[users.models.email_validate])),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Restaurant Owner', 'Restaurant Owner'), ('Admin', 'Admin')], default='Customer', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resto_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
