# Generated by Django 5.1.6 on 2025-02-25 20:01

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(260000)])),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=11, validators=[users.models.phone_validate])),
                ('email_address', models.EmailField(max_length=254, validators=[users.models.email_validate])),
                ('password', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Restaurant Owner', 'Restaurant Owner')], max_length=16)),
            ],
        ),
    ]
