# Generated by Django 5.1.6 on 2025-02-26 04:24

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, validators=[users.models.email_validate, django.core.validators.EmailValidator(message='Enter a valid Ateneo email.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[users.models.user_id_validate]),
        ),
    ]
