# Generated by Django 5.1.6 on 2025-03-19 13:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(error_messages={'unique': 'This Ateneo Student ID has already been registered.'}, primary_key=True, serialize=False, unique=True, validators=[users.models.id_validate]),
        ),
    ]
