# Generated by Django 5.1.6 on 2025-02-26 04:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_address_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(error_messages={'unique': 'This phone number has already been registered.'}, max_length=11, unique=True, validators=[users.models.phone_validate]),
        ),
    ]
