# Generated by Django 5.1.6 on 2025-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resto_id', models.AutoField(primary_key=True, serialize=False)),
                ('resto_name', models.CharField(max_length=30, unique=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
