# Generated by Django 5.1.7 on 2025-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='CuisineType',
        ),
    ]
