# Generated by Django 5.1.6 on 2025-02-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='operating_hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=20),
        ),
    ]
