# Generated by Django 5.1.6 on 2025-02-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_operating_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='operating_hours',
            field=models.CharField(max_length=20),
        ),
    ]
