# Generated by Django 5.1.6 on 2025-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_delete_restaurantowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_owners',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='resto_owner',
            field=models.CharField(default='Default', max_length=30),
            preserve_default=False,
        ),
    ]
