# Generated by Django 5.1.6 on 2025-02-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_operating_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='operating_hours',
        ),
    ]
