# Generated by Django 5.1.6 on 2025-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_operating_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.ManyToManyField(to='restaurants.cuisine'),
        ),
    ]
