# Generated by Django 5.1.6 on 2025-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_cuisine_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.ManyToManyField(to='restaurants.cuisinetype'),
        ),
    ]
