# Generated by Django 5.1.6 on 2025-02-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_cuisinetype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisinetype',
            name='description',
        ),
    ]
