# Generated by Django 5.1.6 on 2025-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_cuisinetype_description'),
        ('users', '0004_alter_user_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='resto_owners',
            field=models.ManyToManyField(to='users.user'),
        ),
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='restaurants.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
