# Generated by Django 5.1.6 on 2025-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_resto_owners_restaurantowner'),
        ('users', '0004_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='resto_owners',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'Restaurant Owner'}, to='users.user'),
        ),
    ]
