# Generated by Django 5.1.6 on 2025-02-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_resto_owners'),
    ]

    operations = [
    ]
