# Generated by Django 5.1.6 on 2025-03-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_no', models.IntegerField(editable=False)),
                ('name', models.CharField(default='Unknown Food Item', max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('is_vegan', models.BooleanField()),
                ('is_halal', models.BooleanField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'item_no')},
            },
        ),
    ]
