# Generated by Django 5.1.6 on 2025-02-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_no', models.IntegerField(editable=False)),
                ('description', models.TextField(max_length=100)),
                ('is_vegan', models.BooleanField()),
                ('is_halal', models.BooleanField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
