# Generated by Django 5.1.6 on 2025-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_no',
            field=models.IntegerField(editable=False),
        ),
    ]
