# Generated by Django 5.1.6 on 2025-02-28 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('restaurant', 'item_no')},
        ),
    ]
