# Generated by Django 5.1.7 on 2025-03-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
