# Generated by Django 5.1.7 on 2025-03-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
